repos:
-   repo: local
    hooks:
    - id: format
      name: format
      language: system
      entry: make format
      types: [python]
    - id: run_cmcs
      name: run_cmcs
      language: system
      entry: make run_cmcs
      types: [python]
