dist: xenial

language: python
python:
    - "3.7.2"

install:
     - make dep
     - make dev

script:
    # run static analysis and format check
    - pip list | grep numpy
    - make run_cmcs

cache:
  directories:
    ~/rl-examples
